"""Plik konfiguracyjny"""

# zmienna zawierajaca warstwy zgodne z rozporzadzeniem 2021
# warstwy w zmiennej są ulozone w kolejnosci zgodnej z reprezentacja graficzna


correct_layers = ['EGB_etykieta',
                          'OT_etykieta',
                          'GES_etykieta',
                          'EGB_JednostkaEwidencyjna',
                          'EGB_ObrebEwidencyjny',
                          'EGB_DzialkaEwidencyjna',
                          'EGB_PunktGraniczny',
                          'EGB_Budynek',
                          'OT_BudynekNiewykazanyWEGIB',
                          'EGB_BlokBudynku',
                          'OT_BlokBudynku',
                          'EGB_ObiektTrwaleZwiazanyZBudynkiem',
                          'EGB_poliliniaKierunkowa',
                          'OT_ObiektTrwaleZwiazanyZBudynkami',
                          'OT_poliliniaKierunkowa',
                          'OT_Budowle',
                          'OT_Ogrodzenia',
                          'OT_Komunikacja',
                          'GES_PrzewodWodociagowy',
                          'GES_UrzadzeniaSiecWodociagowa',
                          'GES_PrzewodKanalizacyjny',
                          'GES_UrzadzeniaSiecKanalizacyjna',
                          'GES_PrzewodElektroenergetyczny',
                          'GES_UrzadzeniaSiecElektroenergetyczna',
                          'GES_PrzewodGazowy',
                          'GES_UrzadzeniaSiecGazowa',
                          'GES_PrzewodCieplowniczy',
                          'GES_UrzadzeniaSiecCieplownicza',
                          'GES_PrzewodTelekomunikacyjny',
                          'GES_UrzadzeniaSiecTelekomunikacyjna',
                          'GES_PrzewodSpecjalny',
                          'GES_UrzadzeniaTechniczneSieciSpecjalnej',
                          'GES_PrzewodNiezidentyfikowany',
                          'GES_UrzadzenieNiezidentyfikowane',
                          'GES_UrzadzeniaTowarzyszczaceLiniowe',
                          'GES_UrzadzeniaTowarzyszaceLiniowe',
                          'GES_InneUrzadzeniaTowarzyszace',
                          'OT_SportIRekreacja',
                          'OT_ZagospodarowanieTerenu',
                          'EGB_KonturUzytkuGruntowego',
                          'EGB_KonturKlasyfikacyjny',
                          'OT_Wody',
                          'OT_Rzedna',
                          'GES_Rzedna',
                          'OT_Skarpa',
                          'OT_poczatekGorySkarpy',
                          'OT_koniecGorySkarpy',
                          'EGB_PrezentacjaGraficzna',
                          'EGB_odnosnik',
                          'OT_PrezentacjaGraficzna',
                          'OT_odnosnik',
                          'GES_PrezentacjaGraficzna',
                          'EGB_Zmiana',
                          'GES_odnosnik']

